table schedule_dim
	lineageTag: ae202d36-49dc-4d3d-a10a-9c23ba3daa87

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: cc72d363-9060-43d1-b869-c87772f9e9ce
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	column job_schedule_type
		dataType: string
		lineageTag: dd89713a-ac67-4579-94eb-1f1879f6db40
		summarizeBy: none
		sourceColumn: job_schedule_type

		annotation SummarizationSetBy = Automatic

	partition schedule_dim = m
		mode: import
		source =
				let
				    Source = job_postings_fact,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"job_id", "job_schedule_type"}),
				    #"Replaced Value (, and)" = Table.ReplaceValue(#"Removed Other Columns",", and",",",Replacer.ReplaceText,{"job_schedule_type"}),
				    #"Replaced Value ( and)" = Table.ReplaceValue(#"Replaced Value (, and)"," and",",",Replacer.ReplaceText,{"job_schedule_type"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Replaced Value ( and)", {{"job_schedule_type", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "job_schedule_type"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"job_schedule_type", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"job_schedule_type", Text.Trim, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Trimmed Text", each true),
				    #"Added Conditional Column" = Table.AddColumn(#"Filtered Rows", "Custom", each if [job_schedule_type] = "" then "Not Specified" else [job_schedule_type]),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"job_schedule_type", "job_schedule_type1"}, {"Custom", "job_schedule_type"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"job_schedule_type1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

